### ISSUE TITLE
No iPerf3 menu found in services

### ISSUE THREAD

**Issue by huajijam** [Gevatter-Tod/luci-app-iperf3#1]
using OpenWrt R24.9.9 / LuCI Master (git-24.182.36151-66d29de)
No iperf3 menu in services menu,
access /cgi-bin/luci/admin/services/iperf3 not found

**Comment by Gevatter-Tod** [comment]
Hi @huajijam,
can you let me know how you installed it?
Have you tried rebooting to see if it pops up then?

I tested on 23.05, which is current stable. I cannot find any Openwrt Release 24.9.9. Can you send me a link where you got that from?

**Comment by huajijam** [comment]
> Hi @huajijam, can you let me know how you installed it? Have you tried rebooting to see if it pops up then?
> 
> I tested on 23.05, which is current stable. I cannot find any Openwrt Release 24.9.9. Can you send me a link where you got that from?

I tried both build it with the firmware and install via ipk
both not working

for 24.9.9, I'm using [this repo](https://github.com/coolsnowwolf/lede)

**Comment by Gevatter-Tod** [comment]
This looks to me like a quite customized fork of Openwrt. I am not sure, if they support the same Luci interface building as the official Openwrt builds. I guess you would need to try to port it to their release.
Have you tried it on any of their stable releases?

**Comment by huajijam** [comment]
> Have you tried it on any of their stable releases?

r u using luci2? I think the fork has not support to luci2

**Comment by Gevatter-Tod** [comment]
Yes, that should be it. The app here is based on java-script and not on lua, which was used for luci in the past.

**Comment by huajijam** [comment]
> Yes, that should be it

can u switch it back to support it?

**Comment by Gevatter-Tod** [comment]
That would require to write the app from scratch, which is out of my scope given that openwrt is moving away from lua anyway. Feel free to fork it!
